name: calculator
org: com.example.calculator
description: Samsung Calculator Clone.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  bloc: ^8.1.1
  charcode: ^1.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_feather_icons: ^2.0.0+1
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  intl: ^0.18.0
  math_expressions: ^2.3.1
  path_provider: ^2.0.14



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  bloc_test: ^9.1.1
 

flutter:
  uses-material-design: true
